name: EA
channels:
  - conda-forge
dependencies:
  - python
  - scipy
  - pyviz/label/earthsim::holoviews
  - pyviz/label/earthsim::panel
  - imageio
  - matplotlib
  - numpy
  - pillow
  - pydensecrf
  - scikit-image